openapi: 3.0.1
info:
  title: Stats API Attendance Section
  description: Operations pertaining to attendance
  version: 1.0.0

paths:
  /api/v1/attendance:
    get:
      tags:
        - Attendance
      summary: Get team attendance
      operationId: getTeamAttendance
      parameters:
        - name: teamId
          in: query
          description: 'Unique Team Identifier. Format: 141, 147, etc'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: integer
              format: int32
        - name: leagueId
          in: query
          description: Comma delimited list of Unique league identifiers
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: integer
              format: int32
        - name: season
          in: query
          description: Comma delimited list of Seasons of play
          required: false
          schema:
            type: array
            items:
              type: string
        - name: leagueListId
          in: query
          description: Unique League List Identifier
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/LeagueListsEnum'
        - name: gameType
          in: query
          description: Type of Game. Available types in /api/v1/gameTypes
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              $ref: '../_schemas/schemas.yml#/components/schemas/GameTypeEnum'
        - name: date
          in: query
          description: 'Date of Game. Format: YYYY-MM-DD'
          required: false
          schema:
            type: string
            format: date
        - name: startDate
          in: query
          description: 'Start date for range of data (must be used with end date). Format: MM/DD/YYYY'
          required: false
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          description: 'End date for range of data (must be used with start date). Format: MM/DD/YYYY'
          required: false
          schema:
            type: string
            format: date
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/AttendanceRestObject'