openapi: 3.0.1
info:
  title: Stats API Bat Tracking
  description: Operations pertaining to bat tracking data
  version: 1.0.0

paths:   
  /api/v1/batTracking/game/{gamePk}/{playId}:
    get:
      tags:
        - Bat Tracking
      summary: View Bat Tracking Data by playId and gameId
      description: This endpoint allows you to pull bat tracking data by gameId and playId
      operationId: batTracking
      parameters:
        - name: gamePk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: playId
          in: path
          description: Unique play identifier
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BatTrackingRestObject'
      security:
        - basicAuth: []
        - bearerAuth: []