openapi: 3.0.1
info:
  title: Stats API Bat Biomechanical
  description: Operations pertaining to biomechanical data
  version: 1.0.0

paths:
  /api/v1/game/{gamePk}/{playId}/analytics/biomechanics/{positionId}:
    get:
      tags:
        - Biomechanics
      summary: View Biomechanical data by playId and gameId filtered by player positionId
      description: This endpoint allows you to pull biomechanical tracking data by gameId and playId filtered by player positionId
      operationId: biomechanical
      parameters:
        - name: gamePk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: playId
          in: path
          description: Unique play identifier
          required: true
          schema:
            type: string
        - name: positionId
          in: path
          description: 'Position number. Format: 1, 2, 3, etc'
          required: true
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/SkeletalDataWrapperRestObject'
      security:
        - basicAuth: []
        - bearerAuth: []
