openapi: 3.0.1
info:
  title: Stats API Broadcast
  description: Operations pertaining to broadcasts
  version: 1.0.0

paths:
  /api/v1/broadcasters:
    get:
      tags:
        - Broadcast
      summary: Get All Active Broadcasters
      operationId: getAllBroadcasters
      parameters:
        - name: activeStatus
          in: query
          description: 'Current status of the broadcaster. Format: Active = y, inactive = n, both = b'
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/BroadcasterActiveStatusEnum'
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '../_schemas/schemas.yml#/components/schemas/BroadcasterRestObject'
  /api/v1/broadcast:
    get:
      tags:
        - Broadcast
      summary: Get Broadcasters
      operationId: getBroadcasts
      parameters:
        - name: broadcasterIds
          in: query
          description: All of the broadcast details
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '../_schemas/schemas.yml#/components/schemas/BroadcasterRestObject'