openapi: 3.0.1
info:
  title: Stats API Division
  description: Operations pertaining to divisions
  version: 1.0.0

paths:  
  /api/v1/divisions:
    get:
      tags:
        - Division
      summary: Get division information
      description: This endpoint allows you to pull divisions
      operationId: divisions
      parameters:
        - name: divisionId
          in: path
          description: Unique Division Identifier
          required: true
          schema:
            type: integer
            format: int32
        - name: includeInactive
          in: query
          description: Whether or not to include inactive
          required: false
          schema:
            type: boolean
            default: false
        - name: leagueId
          in: query
          description: Unique League Identifier
          required: false
          schema:
            type: integer
            format: int32
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: season
          in: query
          description: Season of play
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/DivisionsRestObject'
  /api/v1/divisions/{divisionId}:
    get:
      tags:
        - Division
      summary: Get division information
      description: This endpoint allows you to pull divisions
      operationId: divisions_1
      parameters:
        - name: divisionId
          in: path
          description: Unique Division Identifier
          required: true
          schema:
            type: integer
            format: int32
        - name: includeInactive
          in: query
          description: Whether or not to include inactive
          required: false
          schema:
            type: boolean
            default: false
        - name: leagueId
          in: query
          description: Unique League Identifier
          required: false
          schema:
            type: integer
            format: int32
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: season
          in: query
          description: Season of play
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/DivisionsRestObject'
