openapi: 3.0.1
info:
  title: Stats API Draft
  description: Operations pertaining to MLB BaseballDraft
  version: 1.0.0

paths:    
  /api/v1/draft/{year}/latest:
    get:
      tags:
        - Draft
      summary: Get the last drafted player and the next 5 teams up to pick
      operationId: latestDraftPicks
      parameters:
        - name: year
          in: path
          description: 'Year the player was drafted. Format: 2000'
          required: true
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballDraftLatestRestObject'
  /api/v1/draft/prospects:
    get:
      tags:
        - Draft
      summary: View MLB Draft Prospects
      operationId: draftProspects
      parameters:
        - name: year
          in: path
          description: 'Year the player was drafted. Format: 2000'
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: The pointer to start for a return set; used for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: order
          in: query
          description: The order of sorting, ascending or descending
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/SortOrderEnum'
        - name: sortBy
          in: query
          description: Sort the set of data by the specified field
          required: false
          schema:
            type: string
        - name: drafted
          in: query
          description: Whether or not the players been drafted
          required: false
          schema:
            type: boolean
        - name: round
          in: query
          description: Round in which a player was drafted
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter players by the first letter of their name using using the specific character
          required: false
          schema:
            type: string
        - name: school
          in: query
          description: Filter players by the first letter of their school using using the specific character
          required: false
          schema:
            type: string
        - name: position
          in: query
          description: 'Position number. Format: 1, 2, 3, etc'
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPosition'
        - name: team
          in: query
          description: 'Unique Team Code. Format: tor, nya, etc'
          required: false
          schema:
            type: string
        - name: teamId
          in: query
          description: 'Unique Team Identifier. Format: 141, 147, etc'
          required: false
          schema:
            type: integer
            format: int32
        - name: state
          in: query
          description: 'State where the venue is located. Format: Ohio'
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Filter players by their home country
          required: false
          schema:
            type: string
        - name: playerId
          in: query
          description: A unique identifier for a player
          required: false
          schema:
            type: integer
            format: int32
        - name: bisPlayerId
          in: query
          description: A unique identifier for a player in the EBIS system
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/ProspectListRestObject'
  /api/v1/draft/prospects/{year}:
    get:
      tags:
        - Draft
      summary: View MLB Draft Prospects
      operationId: draftProspects_1
      parameters:
        - name: year
          in: path
          description: 'Year the player was drafted. Format: 2000'
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: The pointer to start for a return set; used for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: order
          in: query
          description: The order of sorting, ascending or descending
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/SortOrderEnum'
        - name: sortBy
          in: query
          description: Sort the set of data by the specified field
          required: false
          schema:
            type: string
        - name: drafted
          in: query
          description: Whether or not the players been drafted
          required: false
          schema:
            type: boolean
        - name: round
          in: query
          description: Round in which a player was drafted
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter players by the first letter of their name using using the specific character
          required: false
          schema:
            type: string
        - name: school
          in: query
          description: Filter players by the first letter of their school using using the specific character
          required: false
          schema:
            type: string
        - name: position
          in: query
          description: 'Position number. Format: 1, 2, 3, etc'
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPosition'
        - name: team
          in: query
          description: 'Unique Team Code. Format: tor, nya, etc'
          required: false
          schema:
            type: string
        - name: teamId
          in: query
          description: 'Unique Team Identifier. Format: 141, 147, etc'
          required: false
          schema:
            type: integer
            format: int32
        - name: state
          in: query
          description: 'State where the venue is located. Format: Ohio'
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Filter players by their home country
          required: false
          schema:
            type: string
        - name: playerId
          in: query
          description: A unique identifier for a player
          required: false
          schema:
            type: integer
            format: int32
        - name: bisPlayerId
          in: query
          description: A unique identifier for a player in the EBIS system
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/ProspectListRestObject'
  /api/v1/draft:
    get:
      tags:
        - Draft
      summary: View MLB Drafted Players
      operationId: draftPicks
      parameters:
        - name: year
          in: path
          description: 'Year the player was drafted. Format: 2000'
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: The pointer to start for a return set; used for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: order
          in: query
          description: The order of sorting, ascending or descending
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/SortOrderEnum'
        - name: sortBy
          in: query
          description: Sort the set of data by the specified field
          required: false
          schema:
            type: string
        - name: drafted
          in: query
          description: Whether or not the players been drafted
          required: false
          schema:
            type: boolean
        - name: round
          in: query
          description: Round in which a player was drafted
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter players by the first letter of their name using using the specific character
          required: false
          schema:
            type: string
        - name: school
          in: query
          description: Filter players by the first letter of their school using using the specific character
          required: false
          schema:
            type: string
        - name: position
          in: query
          description: 'Position number. Format: 1, 2, 3, etc'
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPosition'
        - name: team
          in: query
          description: 'Unique Team Code. Format: tor, nya, etc'
          required: false
          schema:
            type: string
        - name: teamId
          in: query
          description: 'Unique Team Identifier. Format: 141, 147, etc'
          required: false
          schema:
            type: integer
            format: int32
        - name: state
          in: query
          description: 'State where the venue is located. Format: Ohio'
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Filter players by their home country
          required: false
          schema:
            type: string
        - name: playerId
          in: query
          description: A unique identifier for a player
          required: false
          schema:
            type: integer
            format: int32
        - name: bisPlayerId
          in: query
          description: A unique identifier for a player in the EBIS system
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballDraftListRestObject'
  /api/v1/draft/{year}:
    get:
      tags:
        - Draft
      summary: View MLB Drafted Players
      operationId: draftPicks_1
      parameters:
        - name: year
          in: path
          description: 'Year the player was drafted. Format: 2000'
          required: true
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: The pointer to start for a return set; used for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: order
          in: query
          description: The order of sorting, ascending or descending
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/SortOrderEnum'
        - name: sortBy
          in: query
          description: Sort the set of data by the specified field
          required: false
          schema:
            type: string
        - name: drafted
          in: query
          description: Whether or not the players been drafted
          required: false
          schema:
            type: boolean
        - name: round
          in: query
          description: Round in which a player was drafted
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: Filter players by the first letter of their name using using the specific character
          required: false
          schema:
            type: string
        - name: school
          in: query
          description: Filter players by the first letter of their school using using the specific character
          required: false
          schema:
            type: string
        - name: position
          in: query
          description: 'Position number. Format: 1, 2, 3, etc'
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPosition'
        - name: team
          in: query
          description: 'Unique Team Code. Format: tor, nya, etc'
          required: false
          schema:
            type: string
        - name: teamId
          in: query
          description: 'Unique Team Identifier. Format: 141, 147, etc'
          required: false
          schema:
            type: integer
            format: int32
        - name: state
          in: query
          description: 'State where the venue is located. Format: Ohio'
          required: false
          schema:
            type: string
        - name: country
          in: query
          description: Filter players by their home country
          required: false
          schema:
            type: string
        - name: playerId
          in: query
          description: A unique identifier for a player
          required: false
          schema:
            type: integer
            format: int32
        - name: bisPlayerId
          in: query
          description: A unique identifier for a player in the EBIS system
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballDraftListRestObject'
