openapi: 3.0.1
info:
  title: Stats API Game
  description: Operations pertaining to games
  version: 1.0.0

paths:   
  /api/v1/game/{game_pk}/playByPlay:
    get:
      tags:
        - Game
      summary: Get game play By Play
      description: This endpoint allows you to pull the play by play of a game
      operationId: playByPlay
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPlayByPlayRestObject'
  /api/v1/game/{game_pk}/linescore:
    get:
      tags:
        - Game
      summary: Get game linescore
      description: This endpoint allows you to pull the linescore for a game
      operationId: linescore
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballLinescoreRestObject'
  /api/v1/game/{game_pk}/feed/color:
    get:
      tags:
        - Game
      summary: Get game color feed.
      description: 'This API can return very large payloads.  It is STRONGLY recommended that clients ask for diffs and use "Accept-Encoding: gzip" header.'
      operationId: colorFeed
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
  /api/v1/game/{game_pk}/feed/color/timestamps:
    get:
      tags:
        - Game
      summary: Retrieve all of the color timestamps for a game.
      description: This can be used for replaying games.  Endpoint returns all of the timecodes that can be used with diffs for /v1/game/{game_pk}/feed/color
      operationId: colorTimestamps
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: array
                items:
                  type: string
  /api/v1/game/{game_pk}/content:
    get:
      tags:
        - Game
      summary: Retrieve all content for a game.
      operationId: content
      parameters:
        - name: game_pk
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: highlightLimit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/GameContentRestObject'
  /api/v1/game/{game_pk}/boxscore:
    get:
      tags:
        - Game
      summary: Get game boxscore.
      description: This endpoint allows you to pull a boxscore
      operationId: boxscore
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
        - name: numPlayers
          in: query
          description: Number of top player game scores to show. Default is 3.
          required: false
          schema:
            type: integer
            format: int32
            default: 3
        - name: noTies
          in: query
          description: If set to false, will show all players tied for the last spot in the game scores list.
          required: false
          schema:
            type: boolean
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballBoxscoreRestObject'
  /api/v1/game/{gamePk}/withMetrics:
    get:
      tags:
        - Game
      summary: Get game info with metrics
      operationId: getGameWithMetrics
      parameters:
        - name: gamePk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballGameRestObject'
  /api/v1/game/{gamePk}/winProbability:
    get:
      tags:
        - Game
      summary: Get the win probability for this game
      operationId: getWinProbability
      parameters:
        - name: gamePk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '../_schemas/schemas.yml#/components/schemas/BaseballPlayRestObject'
  /api/v1/game/{gamePk}/contextMetrics:
    get:
      tags:
        - Game
      summary: Get the context metrics for this game based on its current state
      operationId: getGameContextMetrics
      parameters:
        - name: gamePk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballGameContextRestObject'
  /api/v1/game/changes:
    get:
      tags:
        - Game
      summary: View a game change log
      operationId: currentGameStats_1
      parameters:
        - name: updatedSince
          in: query
          description: 'Format: YYYY-MM-DDTHH:MM:SSZ'
          required: false
          schema:
            type: string
            format: date-time
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: sportIds
          in: query
          description: Comma delimited list of top level organizations of a sport
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int32
        - name: gameType
          in: query
          description: Type of Game. Available types in /api/v1/gameTypes
          required: false
          schema:
            $ref: '../_schemas/schemas.yml#/components/schemas/GameTypeEnum'
        - name: gameTypes
          in: query
          description: Comma delimited list of type of Game. Available types in /api/v1/gameTypes
          required: false
          schema:
            type: array
            items:
              $ref: '../_schemas/schemas.yml#/components/schemas/GameTypeEnum'
        - name: season
          in: query
          description: Season of play
          required: false
          schema:
            type: string
        - name: gamePks
          in: query
          description: Comma delimited list of unique primary keys
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: integer
              format: int32
        - name: limit
          in: query
          description: Number of results to return
          required: false
          schema:
            type: integer
            format: int32
        - name: offset
          in: query
          description: The pointer to start for a return set; used for pagination
          required: false
          schema:
            type: integer
            format: int32
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/ScheduleRestObject'
  /api/v1.1/game/{game_pk}/feed/live:
    get:
      tags:
        - Game
      summary: Get live game status.
      description: 'This API can return very large payloads.  It is STRONGLY recommended that clients ask for diffs and use "Accept-Encoding: gzip" header.'
      operationId: liveGameV1
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: timecode
          in: query
          description: 'Use this parameter to return a snapshot of the data at the specified time. Format: YYYYMMDD_HHMMSS'
          required: false
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: inclusiveTimecode
          in: query
          description: True to include plays that happen before or at the specified timecode
          required: false
          schema:
            type: boolean
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/BaseballGameRestObject'
  /api/v1.1/game/{game_pk}/feed/live/timestamps:
    get:
      tags:
        - Game
      summary: Retrieve all of the play timestamps for a game.
      description: This can be used for replaying games.  Endpoint returns all of the timecodes that can be used with diffs for /v1/game/{game_pk}/feed/live
      operationId: liveTimestampv11
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string
  /api/v1.1/game/{game_pk}/feed/live/diffPatch:
    get:
      tags:
        - Game
      summary: Get live game status diffPatch.
      description: 'This endpoint allows comparison of game files and shows any differences/discrepancies between the two<br/><br/><b>Diff/Patch System:</b> startTimecode and endTimecode can be used for getting diffs.<br/>Expected usage:  <br/> 1) Request full payload by not passing startTimecode or endTimecode.  This will return the most recent game state.<br/> 2) Find the latest timecode in this response.  <br/> 3) Wait X seconds<br/> 4) Use the timecode from 2 as the startTimecode.  This will give you a diff of everything that has happened since startTimecode.  <br/> 5) If no data is returned, wait X seconds and do the same request.  <br/> 6) If data is returned, get a new timeStamp from the response, and use that for the next call as startTimecode.'
      operationId: liveGameDiffPatchV1
      parameters:
        - name: game_pk
          in: path
          description: Unique Primary Key Representing a Game
          required: true
          schema:
            type: integer
            format: int32
        - name: startTimecode
          in: query
          description: 'Start time code will give you everything since that time. Format: MMDDYYYY_HHMMSS'
          required: false
          schema:
            type: string
        - name: endTimecode
          in: query
          description: 'End time code will give you a snapshot at that specific time. Format: MMDDYYYY_HHMMSS'
          required: false
          schema:
            type: string
        - name: accent
          in: query
          description: Boolean value to specify wanting a person's name with accents or without
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: OK
          content:
            application/json;charset=UTF-8:
              schema:
                type: string