openapi: 3.0.1
info:
  title: Stats API Job
  description: Operations pertaining to jobs
  version: 1.0.0

paths:  
  /api/v1/jobs:
    get:
      tags:
        - Job
      summary: Get jobs by type
      description: This endpoint allows you to pull teams
      operationId: getJobsByType
      parameters:
        - name: jobType
          in: query
          description: Job Type Identifier (ie. UMPR, etc..)
          required: true
          schema:
            type: string
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: date
          in: query
          description: 'Date of Game. Format: YYYY-MM-DD'
          required: false
          schema:
            type: string
            format: date
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/RosterRestObject'
  /api/v1/jobs/umpires:
    get:
      tags:
        - Job
      summary: Get umpires
      description: This endpoint allows you to pull teams
      operationId: umpires
      parameters:
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: date
          in: query
          description: 'Date of Game. Format: YYYY-MM-DD'
          required: false
          schema:
            type: string
            format: date
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
        - name: season
          in: query
          description: Season of play
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/RosterRestObject'
  /api/v1/jobs/umpires/games/{umpireId}:
    get:
      tags:
        - Job
      summary: Get umpires and associated game for umpireId
      description: This endpoint allows you to pull teams
      operationId: umpireSchedule
      parameters:
        - name: umpireId
          in: path
          description: A unique identifier for an umpire
          required: true
          schema:
            type: integer
            format: int32
        - name: season
          in: query
          description: Season of play
          required: true
          schema:
            type: string
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/ScheduleRestObject'
      security:
        - basicAuth: []
        - bearerAuth: []
  /api/v1/jobs/officialScorers:
    get:
      tags:
        - Job
      summary: Get official scorers
      description: This endpoint allows you to pull teams
      operationId: officialScorers
      parameters:
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: date
          in: query
          description: 'Date of Game. Format: YYYY-MM-DD'
          required: false
          schema:
            type: string
            format: date
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/RosterRestObject'
  /api/v1/jobs/datacasters:
    get:
      tags:
        - Job
      summary: Get datacaster jobs
      description: Get datacaster jobs
      operationId: datacasters
      parameters:
        - name: sportId
          in: query
          description: Top level organization of a sport
          required: false
          schema:
            type: integer
            format: int32
        - name: date
          in: query
          description: 'Date of Game. Format: YYYY-MM-DD'
          required: false
          schema:
            type: string
            format: date
        - name: fields
          in: query
          description: 'Comma delimited list of specific fields to be returned. Format: topLevelNode, childNode, attribute'
          required: false
          schema:
            uniqueItems: true
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '../_schemas/schemas.yml#/components/schemas/RosterRestObject'
